name: Build and Publish All Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER_LC: ${{ github.repository_owner }}
  REPO_LC: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: set lower case owner name
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'
    
    - name: set lower case repo name
      run: |
        echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
      env:
        REPO: '${{ github.event.repository.name }}'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ------------------------------
    # Build: Node-RED
    # ------------------------------
    - name: Build & Push Node-RED image
      uses: docker/build-push-action@v5
      with:
        context: ./nodered
        file: ./nodered/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_LC }}-nodered:latest
        build-args: |
          NODERED_SECRET=${{ secrets.NODERED_CREDENTIALSECRET }}

    # ------------------------------
    # Build: InfluxDB
    # ------------------------------
    - name: Build & Push InfluxDB image
      uses: docker/build-push-action@v5
      with:
        context: ./influxdb
        file: ./influxdb/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_LC }}-influxdb:latest
        build-args: |
          INFLUXDB_PASSWORD=${{ secrets.INFLUXDB_PASSWORD }}
          INFLUXDB_TOKEN=${{ secrets.INFLUXDB_TOKEN }}

    # ------------------------------
    # Build: Mosquitto
    # ------------------------------
    - name: Build & Push Mosquitto image
      uses: docker/build-push-action@v5
      with:
        context: ./mosquitto
        file: ./mosquitto/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_LC }}-mosquitto:latest

    # ------------------------------
    # Build: Python App (image/)
    # ------------------------------
    - name: Build & Push Controller Python image
      uses: docker/build-push-action@v5
      with:
        context: ./image
        file: ./image/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_LC }}-controller:latest